import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

if (!process.env.ANTHROPIC_API_KEY) {
  console.error('Error: ANTHROPIC_API_KEY environment variable not set');
  process.exit(1);
}

// Import questions using relative path
const pmQuestions = (await import('../src/data/pmQuestions.js')).pmQuestions;

// Extract all questions
function extractQuestions(pmQuestions) {
  const questions = [];
  for (const [level, bank] of Object.entries(pmQuestions || {})) {
    if (!bank) continue;
    for (const [cat, qList] of Object.entries(bank)) {
      if (!Array.isArray(qList)) continue;
      for (const q of qList) {
        questions.push({ q: q.q, a: q.a, level, category: cat });
      }
    }
  }
  return questions;
}

const allQuestions = extractQuestions(pmQuestions);
const questions = allQuestions.slice(1435, 1549);
console.log(`Found ${questions.length} questions to improve\n`);

// Improve answers
const improved = [];
for (let i = 0; i < questions.length; i++) {
  const { q, a, level, category } = questions[i];

  const prompt = `You are an expert PM interview coach. Rewrite this expert answer so it sounds exactly like a confident, experienced PM speaking in a real interview.

Rules:
- Write in first person, conversational tone
- Start with clarifying questions the candidate would ask (2-3 questions), then say what assumptions they are making
- Use natural spoken language - no bullet points, no headers, no bold text, no markdown formatting
- Flow as continuous paragraphs like actual speech
- Include: problem framing, approach, specific features/metrics, trade-offs, and how you would validate
- Length: 250-350 words
- No em dashes, no asterisks, no special characters
- Sound like a human speaking, not a report being read

Question: ${q}
Current answer: ${a}

Return ONLY the rewritten conversational answer. No headers, no bullet points, no markdown.`;

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 1000,
        messages: [{
          role: 'user',
          content: prompt
        }]
      })
    });

    const data = await response.json();
    const improvedAnswer = data.content[0].text;

    improved.push({
      q,
      a: improvedAnswer,
      level,
      category,
      original_a: a,
    });

    console.log(`Improved ${i + 1}/${questions.length}`);

    // Delay 1 second between calls
    if (i < questions.length - 1) {
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  } catch (error) {
    console.error(`Error improving question ${i + 1}:`, error.message);
  }
}

// Write results
const outputPath = path.join(__dirname, '../src/data/pmQuestions_conversational_batch3.js');
const output = `// Conversational PM answers generated by scripts/improve_expert_answers.mjs
// Generated: ${new Date().toISOString()}

export const pmQuestionsConversational_batch3 = ${JSON.stringify(improved, null, 2)};
`;

fs.writeFileSync(outputPath, output, 'utf-8');
console.log(`\nSaved ${improved.length} conversational answers to ${outputPath}`);
