import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CAREER_TRACKS = [
  'B2C / Consumer PM',
  'B2B / Enterprise PM',
  'Growth PM',
  'Technical PM',
  'Data / AI PM',
  'Hardware PM',
  'Web3 / Crypto PM',
  'Internal Tools PM',
  'Localization PM',
  'Product Operations',
  'Product Marketing Manager',
];

async function callClaudeAPI(question) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY environment variable not set');
  }

  const tracksString = CAREER_TRACKS.map((t) => `- ${t}`).join('\n');

  const prompt = `Given this PM interview question, which career tracks is it most relevant for? Choose 1-3 from the list. Return only a JSON array of track names.

Question: "${question}"

Available tracks:
${tracksString}

Example response format: ["B2C / Consumer PM", "Growth PM"]

IMPORTANT: Return ONLY the JSON array, nothing else.`;

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-opus-4-6',
      max_tokens: 256,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`Claude API error: ${response.status} - ${JSON.stringify(error)}`);
  }

  const data = await response.json();
  const content = data.content[0].text;

  // Parse JSON from response
  const jsonMatch = content.match(/\[[\s\S]*?\]/);
  if (!jsonMatch) {
    console.warn(`Could not parse JSON from response: ${content}`);
    return [];
  }

  try {
    return JSON.parse(jsonMatch[0]);
  } catch (e) {
    console.warn(`Failed to parse JSON: ${jsonMatch[0]}`);
    return [];
  }
}

async function main() {
  const pmQuestionsPath = path.join(__dirname, '../src/data/pmQuestions.js');

  // Import the module dynamically
  const module = await import(pathToFileURL(pmQuestionsPath).href);
  const { pmQuestions } = module;

  if (!pmQuestions || typeof pmQuestions !== 'object') {
    throw new Error('Could not find pmQuestions object in module');
  }

  // Flatten nested structure: pmQuestions[level][category] = questions array
  const allQuestions = [];
  for (const level in pmQuestions) {
    const levelData = pmQuestions[level];
    if (typeof levelData === 'object' && levelData !== null) {
      for (const category in levelData) {
        const categoryQuestions = levelData[category];
        if (Array.isArray(categoryQuestions)) {
          allQuestions.push(...categoryQuestions);
        }
      }
    }
  }

  console.log(`Found ${allQuestions.length} total questions`);

  // Process first 100 questions
  const questionsToProcess = allQuestions.slice(100, 1549);
  console.log(`Processing first ${questionsToProcess.length} questions...\n`);

  const trackedQuestions = [];

  for (let i = 0; i < questionsToProcess.length; i++) {
    const question = questionsToProcess[i];
    const questionText = typeof question === 'string' ? question : (question.q || question.question);

    try {
      const displayText = questionText.substring(0, 50).replace(/\n/g, ' ');
      console.log(`[${i + 1}/${questionsToProcess.length}] ${displayText}...`);

      const tracks = await callClaudeAPI(questionText);

      const trackedQuestion = { ...question, tracks };

      trackedQuestions.push(trackedQuestion);

      // 1 second delay between API calls
      if (i < questionsToProcess.length - 1) {
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    } catch (error) {
      console.error(`Error processing question ${i + 1}:`, error.message);
      // Add question without tracks on error
      const trackedQuestion = typeof question === 'string'
        ? { question, tracks: [] }
        : { ...question, tracks: [] };
      trackedQuestions.push(trackedQuestion);
    }
  }

  // Save to output file
  const outputPath = path.join(__dirname, '../src/data/pmQuestions_tracked_batch2.js');
  const outputContent = `// Auto-generated file with career track tags
// Generated by scripts/tag_career_tracks.mjs

export const pmQuestions_tracked_batch2 = ${JSON.stringify(trackedQuestions, null, 2)};
`;

  fs.writeFileSync(outputPath, outputContent, 'utf-8');
  console.log(`\n✓ Successfully saved ${trackedQuestions.length} tracked questions to ${outputPath}`);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
